---
# Copyright (c) 2024, Mikhail Vorontsov (@mephs) <mvorontsov@tuta.io>

# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

namespace: mephs
name: proxmox
version: 1.0.0
readme: README.md
authors:
  - Mikhail Vorontsov <mvorontsov@tuta.io>
description: Managing the Proxmox VE cluster via the Proxmox VE API.
license:
  - GPL-3.0-or-later
license_file: LICENSE
tags: ['application', 'proxmox', 'pve']
repository: https://github.com/mephs/ansible-collection-proxmox
documentation: https://github.com/mephs/ansible-collection-proxmox/README.md
homepage: https://github.com/mephs/ansible-collection-proxmox
issues: https://github.com/mephs/ansible-collection-proxmox/issues
