---
# Copyright (c) 2024, Mikhail Vorontsov
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

namespace: rusmephist
name: proxmox
version: 1.0.0
readme: README.md
authors:
  - Mikhail Vorontsov (mikevoroncov@gmail.com)
description: Manage the Proxmox cluster via the Proxmox VE API.
license:
  - GPL-3.0-or-later
license_file: LICENSE
tags: ['proxmox', 'pve']
repository: https://github.com/rusmephist/ansible-modules
documentation: https://github.com/rusmephist/ansible-modules/proxmox/README.md
homepage: https://github.com/rusmephist/ansible-modules/proxmox
issues: https://github.com/RusMephist/ansible-modules/issues
